### PR TITLE
promote noise-libp2p spec to maturity stage 3A

### PR DESCRIPTION
**Pull request by raulk**
This spec now satisfies the conditions to be considered an ACTIVE RECOMMENDATION.

The two known interoperable implementations are:

* go-libp2p-noise: https://github.com/libp2p/go-libp2p-noise
* js-libp2p-noise: https://github.com/NodeFactoryIo/js-libp2p-noise

---

ping @raulk, @tomaka, @romanb, @shahankhatch, @Mikerah, @djrtwo, @dryajov, @mpetrunic, @AgeManning, @morrigan, @araskachoi, @mhchia

Conformant to our [spec lifecycle process](https://github.com/libp2p/specs/blob/master/00-framework-01-spec-lifecycle.md), you have 10 days to dispute the promotion ;-)

### CODE REVIEW

**Comment by raulk** [comment]
@romanb do we consider rust-libp2p to be interoperable with r2 of the noise-libp2p spec? AFAIK, the rust-libp2p implementation predates the spec, so I'm uncertain.

@shahankhatch have you guys been able to test the jvm-libp2p Noise implementation against go-libp2p and js-libp2p?

**Comment by romanb** [comment]
> @romanb do we consider rust-libp2p to be interoperable with r2 of the noise-libp2p spec? AFAIK, the rust-libp2p implementation predates the spec, so I'm uncertain.

It is not currently compatible, however, the differences are minor as far as I am aware, i.e. some naming and the domain separation for the static DH key signatures. There is already a PR that should make `rust-libp2p` fully compatible: https://github.com/libp2p/rust-libp2p/pull/1545.

**Comment by djrtwo** [comment]
cc: @ajsutton (I believe Shahan is no longer working on Teku/jvm-libp2p)

**Comment by ajsutton** [comment]
@Nashatyrev has taken over looking at jvm-libp2p's Noise implementation.  I believe it now works with go-libp2p successfully.  It was working with rust-libp2p prior to the latest spec tweak (I'm vague on the details).

**Comment by Nashatyrev** [comment]
> @shahankhatch have you guys been able to test the jvm-libp2p Noise implementation against go-libp2p and js-libp2p?

@raulk 
- The release `0.3.4` (https://github.com/libp2p/jvm-libp2p/pull/100) should be compatible with Go impl. 
- Didn't interopped with JS. 
- As for Rust, 
  - I interopped with the Lighthouse Rust Libp2p fork (https://github.com/sigp/rust-libp2p).  It still pending to integrate latest Noise changes (remove handshake payload length bytes). We now have a temp compatibility flag 
  - The original rust-libp2p didn't conform the spec (at least it didn't support simple `/noise` protocol name) last time I tried it (around 2-3 weeks ago)

**Comment by tomaka** [comment]
> The original rust-libp2p didn't conform the spec (at least it didn't support simple /noise protocol name) last time I tried it (around 2-3 weeks ago)

As mentioned above, there is a PR that should make it compatible: https://github.com/libp2p/rust-libp2p/pull/1545

**Comment by mhchia** [comment]
[py-libp2p](https://github.com/libp2p/py-libp2p/blob/master/libp2p/security/noise/patterns.py) should have worked with the go implementation as well. We have an interop test in CI to test against it.

**Comment by jacobheun** [comment]
As this has been sitting well beyond the requisite 10 days, I am merging this.

**Pull request merged**
