### PR TITLE
Create LICENSE (MIT)

### LINKED ISSUE #632: What is the license for the project?
Hello,

what is the license for the specifications?  I noticed that there's no `COPYING` or 'LICENSE` file in the repository, not even a mention of  the license in `README.md`.

Maybe you could explicitly use some kind of Creative Commons license, or maybe GNU FDL if it is possible?

Thanks!

-avp

### PR DESCRIPTION
**Pull request by MarcoPolo**
closes #632

### CODE REVIEW

**Review by vyzo — APPROVED** [review]

**Review by vyzo — CHANGES_REQUESTED** [review]
You know, lets discuss the license with the community.

MIT is not appropriate for specifications i think.
Creative Commons or a license similar to what the IETF does would be more appropriate

**Comment by marten-seemann** [comment]
Can you just impose a license on contributions after the fact?

People have already made [license-free](https://en.wikipedia.org/wiki/License-free_software) contributions for close to a decade now. ianal, but I'd be very surprised if you could put all of their work under a license without first getting explicit consent from each and every contributor.

**Comment by vyzo** [comment]
Closing this, @marten-seemann is right, we can't do that without explicit permission from contributors.

**Comment by MarcoPolo** [comment]
You’re right. Let’s discuss on the issue

**Pull request closed without merging**
