### PR TITLE
[Rendezvous] Change `ttl` and `limit` to `uint64`

### PR DESCRIPTION
**Pull request by thomaseizinger**
To be meaningful, TTL has to be a positive integer hence the use of
an signed integer does not bring any value and only introduces
unnecessary error handling.

### CODE REVIEW

**Comment by mxinden** [comment]
I am guessing you meant to write:

```diff
- hence the use of an unsigned integer does not bring any value
+ hence the use of a signed integer does not bring any value
```

I agree, though I don't think we can just alter the type as that would be a breaking protobuf change while this protocol is already used in the wild. @vyzo @vasco-santos can you comment here?

**Comment by thomaseizinger** [comment]
> I am guessing you meant to write:
> 
> ```diff
> - hence the use of an unsigned integer does not bring any value
> + hence the use of a signed integer does not bring any value
> ```
> 
> I agree, though I don't think we can just alter the type as that would be a breaking protobuf change while this protocol is already used in the wild. @vyzo @vasco-santos can you comment here?
> 

Yep will fix that!

Re breaking change: How does the protocol being a Draft affect this? I would have assumed that prior to being finalized, we can make breaking changes. It is not particularly nice for implementations but the way I see it, early adoptions of protocols have to accept that?

**Comment by thomaseizinger** [comment]
@mxinden I've changed the commit message to say "signed integer".

**Comment by thomaseizinger** [comment]
In the same spirit, I changed `limit` of `Discover` to a `uint64`.

**Review by mxinden — APPROVED** [review]
After a bit of research it seems like the rendezvous protocol isn't used anywhere yet, thus the breaking changes here are fine by me. Thanks for cleaning these types up Thomas!

Would you mind bumping the spec revision?

```diff
diff --git a/rendezvous/README.md b/rendezvous/README.md
index 4d98b2f..9277d40 100644
--- a/rendezvous/README.md
+++ b/rendezvous/README.md
@@ -2,7 +2,7 @@
 
 | Lifecycle Stage | Maturity      | Status | Latest Revision |
 |-----------------|---------------|--------|-----------------|
-| 1A              | Working Draft | Active | r1, 2019-01-18  |
+| 1A              | Working Draft | Active | r2, 2021-06-24  |
 
 Authors: [@vyzo]
```

**Comment by thomaseizinger** [comment]
> Would you mind bumping the spec revision?

Done!

**Comment by mxinden** [comment]
Thanks @thomaseizinger!

**Pull request merged**
