### PR TITLE
Adapt existing specs to lifecycle framework

### PR DESCRIPTION
**Pull request by yusefnapora**
Hey all, I've been going through the existing specs and trying to see how they fit to the lifecycle / maturity framework from #169.

Here's what I came up with:

| Spec       | Stage | Authors                         | Interest Group                                     |
|------------|-------|---------------------------------|----------------------------------------------------|
| mdns       | 3A    | @richardschneider               | @raulk, @daviddias                                 |
| identify   | 3A    | @vyzo                           | @tomaka, @richardschneider, @Stebalien, @bigs      |
| mplex      | 3A    | @daviddias, @Stebalien, @tomaka | @richardschneider, @jacobheun                      |
| pnet       | 3A    | @Kubuxu                         | @jacobheun, @lgierth, @daviddias                   |
| pubsub     | 3A    | @whyrusleeping                  | @raulk, @vyzo, @Stebalien, @jamesray1              |
| gossipsub  | 3A    | @vyzo                           | @raulk, @whyrusleeping, @Stebalien, @jamesray1     |
| episub     | 3A    | @vyzo                           | @raulk, @whyrusleeping, @Stebalien, @jamesray1     |
| relay      | 3A    | @daviddias                      | @lgierth, @hsanjuan, @jamesray1, @vyzo             |
| rendezvous | 1A    | @vyzo                           | @daviddias, @whyrusleeping, @Stebalien, @jacobheun |
| tls        | 2A    | @marten-seemann                 | @Stebalien, @jacobheun, @raulk, @Kubuxu            |

I'm also in all the Interest Groups, but I got tired of typing my own handle 😛

I mostly grabbed people out of the PR discussions to put into interest groups. If you see yourself in any and don't want to be, please speak up!

Likewise, @libp2p/go-team, @libp2p/javascript-team, @libp2p/rust-team if you *dont* see yourself and wouldn't mind joining an interest group, let me know.

My feeling is that the Interest Groups for these specs will be pretty low-overhead in terms of attention needed, at least compared to new and developing specs.

I categorized everything as 3A (Recommendation/Active) except for rendezvous (since it seems to still be a working draft), and TLS 1.3, which I marked as a Candidate Recommendation since it's go-only at the moment.

All feedback welcome :)

### CODE REVIEW

**Comment by vasco-santos** [comment]
Hey @yusefnapora 

I would like to join the interest group for Pubsub, Gossipsub, and Episub if possible

**Comment by yusefnapora** [comment]
awesome thanks @vasco-santos

**Comment by jacobheun** [comment]
I'll join the IG for MDNS.

**Comment by yusefnapora** [comment]
I'm going to go ahead and merge this in - if anyone ended up in the wrong groups or would like to add yourself to one, just submit a new PR to fix things up. Thanks all!

**Pull request merged**
